apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nats-webhook-configmap-reader
  namespace: knative-eventing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventing-config-reader
subjects:
  - kind: ServiceAccount
    name: nats-webhook
    namespace: knative-eventing