apiVersion: v1
kind: Namespace
metadata:
  name: my-ns
---
apiVersion: messaging.knative.dev/v1alpha1
kind: NatsJetStreamChannel
metadata:
  name: my-default-channel
  namespace: my-ns
  annotations:
    eventing.knative.dev/scope: namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-nats
  namespace: my-ns
data:
  eventing-nats: |
    url: nats://nats.nats-io.svc.cluster.local
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: my-ns
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: display
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
          ports:
            - containerPort: 8080
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping
  namespace: my-ns
spec:
  schedule: "* * * * *"
  contentType: "application/json"
  data: |
    { "message": "Hello, World!" }
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1alpha1
      kind: NatsJetStreamChannel
      name: my-default-channel
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: subscription
  namespace: my-ns
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: NatsJetStreamChannel
    name: my-default-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: dead-letter-display
---
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dead-letter-display
  namespace: my-ns
spec:
  template:
    spec:
      containers:
        - name: display
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
          ports:
            - containerPort: 8080

