apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jetstream-ch-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jetstream-ch-controller
subjects:
  - kind: ServiceAccount
    name: jetstream-ch-controller
    namespace: knative-eventing